# Generated by Django 5.1.3 on 2025-01-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_volunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
