# Generated by Django 5.1.3 on 2025-02-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustcare', '0002_tbl_volunteer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_volunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
