# Generated by Django 5.1.3 on 2025-02-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustcare', '0003_alter_tbl_volunteer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_volunteer',
            name='availabity',
            field=models.BooleanField(default=True),
        ),
    ]
