# Generated by Django 5.1.3 on 2025-02-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustcare', '0004_tbl_volunteer_availabity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_volunteer',
            old_name='availabity',
            new_name='availability',
        ),
    ]
